name: Mirroring

on: [push, delete]

jobs:
  to_gitcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitcode.net:shenlw66/dotfiles.git
          ssh_private_key:
            ${{ secrets.GITCODE_SSH_PRIVATE_KEY }}

  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          # Such as https://github.com/wangchucheng/git-repo-sync.git
          target-url: https://gitlab.lab.slinvent.com/${{ secrets.GITLAB_USERNAME }}/dotfiles.git
          # Such as wangchucheng
          target-username: ${{ secrets.GITLAB_USERNAME }}
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS_TOKEN }}
          target-token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
